### ISSUE TITLE
Many problems when using `msbt.py` with python3

### ISSUE THREAD

**Issue by v1993** [ObsidianX/3dstools#25]
Currently trying to get `msbt.py` to work. Problems so far:

* `Invalid header magic bytes: b'MsgStdBn' (expected MsgStdBn)`. Fixed by replacing `MSBT_MAGIC = 'MsgStdBn'` with `MSBT_MAGIC = b'MsgStdBn'`
* `Invalid file size reported: 1614020608 (OS reports 13408)` Weird but doesn't seem fatal

```
Traceback (most recent call last):
  File "/home/v/Downloads/msbt.py", line 624, in <module>
    msbt.to_json(args.json)
  File "/home/v/Downloads/msbt.py", line 164, in to_json
    label_lists = self.sections['LBL1']['data']
KeyError: 'LBL1'
```

Stuck with this one right now. Changing `'LBL1'` to `b'LBL1'` doesn't help.

**Comment by v1993** [comment]
I've managed to get further using python2, but still stuck with an error

```
Traceback (most recent call last):
  File "/home/v/Downloads/msbt.1.py", line 624, in <module>
    msbt.to_json(args.json)
  File "/home/v/Downloads/msbt.1.py", line 169, in to_json
    value = self.sections['TXT2']['data'][id_]
KeyError: 'TXT2'
```
