### ISSUE TITLE
Error extracting .bffnt file

### ISSUE THREAD

**Issue by Seijuurou-Hiko** [ObsidianX/3dstools#38]
I'm trying to extract 2 .bffnt file with bffnt.py (need to add more chars), and I get this error:

```
E:\Jogos\Tools\3DS Data Tools\3dstools-master>bffnt.py -xf FOT-PopJoy_Std.bffnt
Traceback (most recent call last):
  File "E:\Jogos\Tools\3DS Data Tools\3dstools-master\bffnt.py", line 1232, in <module>
    bffnt.read(args.file)
  File "E:\Jogos\Tools\3DS Data Tools\3dstools-master\bffnt.py", line 149, in read
    self._parse_header(data[:FFNT_HEADER_SIZE])
  File "E:\Jogos\Tools\3DS Data Tools\3dstools-master\bffnt.py", line 550, in _parse_header
    print('Unknown version: 0x%08x (expected 0x%08x)' % (version, VERSION))
                                                         ^^^^^^^
NameError: name 'version' is not defined
```
```
E:\Jogos\Tools\3DS Data Tools\3dstools-master>bffnt.py -xf MARIO-OutlineL.bffnt
Traceback (most recent call last):
  File "E:\Jogos\Tools\3DS Data Tools\3dstools-master\bffnt.py", line 1232, in <module>
    bffnt.read(args.file)
  File "E:\Jogos\Tools\3DS Data Tools\3dstools-master\bffnt.py", line 149, in read
    self._parse_header(data[:FFNT_HEADER_SIZE])
  File "E:\Jogos\Tools\3DS Data Tools\3dstools-master\bffnt.py", line 550, in _parse_header
    print('Unknown version: 0x%08x (expected 0x%08x)' % (version, VERSION))
                                                         ^^^^^^^
NameError: name 'version' is not defined
```

Same error to both files.

**Comment by jgavrus** [comment]
rename version -> self.version and VERSION -> VERSIONS
